export const DataForum = [
  {
    title: "Altcoin apa yang akan terbang",
    username: "Rizal Herliansyah Hidayat",
    waktu: "1 jam yang lalu",
    tanggal: "12-12-2023",
    body: " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum provident libero hic in mollitia placeat, totam vero nam! Velit fuga laudantium sed iusto ea sint ab ducimus ad voluptates perferendis?",
    kategori: 1,
    tag: "#USDT #BUSD",
    jumlah_like: 10,
    jumlah_dislike: 5,
    jumlah_comment: 2,
  },
  {
    title: "Bitcoin adalah pengganti mata uang",
    username: "Ramdan Purnama",
    waktu: "2 jam yang lalu",
    tanggal: "12-12-2023",
    body: " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum provident libero hic in mollitia placeat, totam vero nam! Velit fuga laudantium sed iusto ea sint ab ducimus ad voluptates perferendis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum provident libero hic in mollitia placeat, totam vero nam! Velit fuga laudantium sed iusto ea sint ab ducimus ad voluptates perferendis?",
    kategori: 2,
    tag: "#BTC #BUSD",
    jumlah_like: 9,
    jumlah_dislike: 2,
    jumlah_comment: 1,
  },
  {
    title: "Federal reserve akan menjadikan bitcoin cadangan devisa",
    username: "Rian Maulana",
    waktu: "4 jam yang lalu",
    tanggal: "12-12-2023",
    body: " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum provident libero hic in mollitia placeat, totam vero nam! Velit fuga laudantium sed iusto ea sint ab ducimus ad voluptates perferendis?",
    kategori: 3,
    tag: "#FEDs",
    jumlah_like: 100,
    jumlah_dislike: 2,
    jumlah_comment: 1,
  },
  {
    title: "Crypto punya banyak sektornya",
    username: "Wulan",
    waktu: "6 jam yang lalu",
    tanggal: "12-12-2023",
    body: " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum provident libero hic in mollitia placeat, totam vero nam! Velit fuga laudantium sed iusto ea sint ab ducimus ad voluptates perferendis?",
    kategori: 4,
    tag: "#USDT #BUSD",
    jumlah_like: 23,
    jumlah_dislike: 1,
    jumlah_comment: 8,
  },
];
